import { includeIgnoreFile } from 'eslint/config'
import path from 'path'
import { fileURLToPath } from 'url'
import cfg from '@fingerprintjs/eslint-config-dx-team/type-checked'
import react from '@eslint-react/eslint-plugin'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import nextPlugin from '@next/eslint-plugin-next'

const __dirname = fileURLToPath(new URL('.', import.meta.url))

// The two Next.js examples additionally get Next's own lint rules. This uses
// @next/eslint-plugin-next directly rather than eslint-config-next: the latter
// bundles eslint-plugin-react, which only supports ESLint <10 and crashes on
// this repo's ESLint 10.
const NEXT_EXAMPLE_FILES = ['examples/next/**/*.{js,jsx,ts,tsx}', 'examples/next-appDir/**/*.{js,jsx,ts,tsx}']

const config = [
  includeIgnoreFile(path.resolve(__dirname, '.gitignore')),
  {
    // next-env.d.ts is regenerated by `next build`/`next dev` on every run (and says
    // "should not be edited"), so linting/formatting a committed copy of it is futile.
    ignores: [
      'examples/**/build/**',
      'examples/**/dist/**',
      'examples/**/.next/**',
      'examples/**/node_modules/**',
      'examples/**/next-env.d.ts',
    ],
  },
  ...cfg,
  {
    files: ['**/*.{ts,tsx}'],
    ...react.configs['recommended-type-checked'],
  },
  reactHooks.configs.flat['recommended-latest'],
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.eslint.json',
        tsconfigRootDir: __dirname,
      },
    },
  },
  {
    files: NEXT_EXAMPLE_FILES,
    ...nextPlugin.configs['core-web-vitals'],
    settings: {
      // Without this, rules like no-html-link-for-pages default to looking for
      // pages/app at the repo root and silently no-op, since both examples live
      // under examples/.
      next: { rootDir: ['examples/next', 'examples/next-appDir'] },
    },
  },
  {
    // peerDependencies declare react >=18 <20, so React 19-only idioms (the `use` hook,
    // bare `<Context>` as a provider) would break React 18 consumers.
    files: ['src/**/*.{ts,tsx}', '__tests__/**/*.{ts,tsx}'],
    rules: {
      '@eslint-react/no-use-context': 'off',
      '@eslint-react/no-context-provider': 'off',
    },
  },
  {
    files: ['examples/preact/**/*.{ts,tsx}', 'examples/**/vite.config.ts'],
    ...tseslint.configs.disableTypeChecked,
  },
  {
    files: ['**/*.{js,mjs,cjs,jsx}'],
    ...tseslint.configs.disableTypeChecked,
  },
  {
    files: ['__tests__/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
    },
  },
]

export default config
